// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqHsa2KA-gPm0sQXoKXfq48_YYARQmxmY',
    appId: '1:1000988449558:web:ddaa95e074b21b1a5c0e37',
    messagingSenderId: '1000988449558',
    projectId: 'e-commerce-104ac',
    authDomain: 'e-commerce-104ac.firebaseapp.com',
    storageBucket: 'e-commerce-104ac.firebasestorage.app',
    measurementId: 'G-RMGYM6DHLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgGDqFqhJbnofXF2KINL-sy4AquyNjPoc',
    appId: '1:1000988449558:android:02fca1566405afd35c0e37',
    messagingSenderId: '1000988449558',
    projectId: 'e-commerce-104ac',
    storageBucket: 'e-commerce-104ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7G7RPTpXEy-vFwzze-3y_bh1jSeLC2bo',
    appId: '1:1000988449558:ios:030d0554a467c2d75c0e37',
    messagingSenderId: '1000988449558',
    projectId: 'e-commerce-104ac',
    storageBucket: 'e-commerce-104ac.firebasestorage.app',
    iosBundleId: 'com.example.fruit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7G7RPTpXEy-vFwzze-3y_bh1jSeLC2bo',
    appId: '1:1000988449558:ios:030d0554a467c2d75c0e37',
    messagingSenderId: '1000988449558',
    projectId: 'e-commerce-104ac',
    storageBucket: 'e-commerce-104ac.firebasestorage.app',
    iosBundleId: 'com.example.fruit',
  );

}