// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6Vl4Z1L2U4FMeNUfu1KFrPDbeSAfi0lA',
    appId: '1:773582405408:web:9150d648b795947ea36145',
    messagingSenderId: '773582405408',
    projectId: 'e-commerce-e902b',
    authDomain: 'e-commerce-e902b.firebaseapp.com',
    storageBucket: 'e-commerce-e902b.firebasestorage.app',
    measurementId: 'G-K433MQJ9ET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4Guju7RjhFuCw-b6ioLikW453fuiWmUE',
    appId: '1:773582405408:android:5439ec9b6868e783a36145',
    messagingSenderId: '773582405408',
    projectId: 'e-commerce-e902b',
    storageBucket: 'e-commerce-e902b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUAkVgr-NTnJ5i2EI9U-5PlFWI6ydx6nc',
    appId: '1:773582405408:ios:f8e3958556cebf11a36145',
    messagingSenderId: '773582405408',
    projectId: 'e-commerce-e902b',
    storageBucket: 'e-commerce-e902b.firebasestorage.app',
    iosBundleId: 'com.example.fruit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUAkVgr-NTnJ5i2EI9U-5PlFWI6ydx6nc',
    appId: '1:773582405408:ios:f8e3958556cebf11a36145',
    messagingSenderId: '773582405408',
    projectId: 'e-commerce-e902b',
    storageBucket: 'e-commerce-e902b.firebasestorage.app',
    iosBundleId: 'com.example.fruit',
  );
}
